# Generated by Django 5.1.4 on 2025-12-24 04:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Географическая точка (широта, долгота)', srid=4326)),
                ('title', models.CharField(help_text='Название точки', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание точки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='points.geopoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geopoint',
            index=models.Index(fields=['user', '-created_at'], name='points_poin_user_id_273e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['point', '-created_at'], name='points_mess_point_i_c81cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', '-created_at'], name='points_mess_user_id_ad80b7_idx'),
        ),
    ]
